/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/apple_vision_pro.glb --transform 
Files: public/models/apple_vision_pro.glb [26.63MB] > apple_vision_pro-transformed.glb [4.77MB] (82%)
Author: polyman (https://sketchfab.com/ely.haddad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-vision-pro-edd3725719174d0ea304951f027f7770
Title: Apple vision pro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/apple_vision_pro-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.QhrnVPOicWtvLUp_0.geometry} material={materials.QJmlgwDEbdXYvzP} scale={0.01} />
      <mesh geometry={nodes.PVOUotyrbUDcmKn_0.geometry} material={materials.dchowTLVLdtpwOG} scale={0.01} />
      <mesh geometry={nodes.uaItrlvyJBCmsWe_0.geometry} material={materials.whSXYrrGCcrfuxx} scale={0.01} />
      <mesh geometry={nodes.nViygjiFUrfDhlT_0.geometry} material={materials.jKQzMSnENjsUseS} scale={0.01} />
      <mesh geometry={nodes.KXKrTLKbZaTffRt_0.geometry} material={materials.EdonOHFdQdHoFXr} scale={0.01} />
      <mesh geometry={nodes.ZCcaowLCvLuOIEe_0.geometry} material={materials.crCMcXBIdLPtHLT} scale={0.01} />
      <mesh geometry={nodes.mBEcqIxhwysXWjK_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh geometry={nodes.xvqAtyUEENxGfCb.geometry} material={materials.YdIpDxDXbAsVHMQ} scale={0.01} />
      <mesh geometry={nodes.xVRkJkrThGqWPjD.geometry} material={materials.SYbdCiSESBmFjUo} scale={0.01} />
      <mesh geometry={nodes.lRBposZgZMkJAEr.geometry} material={materials.zVVmDVDPlfMpRxG} scale={0.01} />
      <mesh geometry={nodes.nOPDxFQcOFWszUY.geometry} material={materials.eNCqvCkKqhectVO} scale={0.01} />
      <mesh geometry={nodes.LRPJoPMDqDtGkvF.geometry} material={materials.felBkYYvBdCgmgt} scale={0.01} />
      <mesh geometry={nodes.wvgJxJWzwbdjtFr.geometry} material={materials.ScnKAQqcZQBxQCT} scale={0.01} />
      <mesh geometry={nodes.SjIzFOhzAplhSmH.geometry} material={materials.dIvnxGToaAftxFb} scale={0.01} />
      <mesh geometry={nodes.iNQQhdMWDhQJBcm.geometry} material={materials.jCwEUxocVEcpgfO} scale={0.01} />
      <mesh geometry={nodes.mpawGWMaOvRqivW.geometry} material={materials.GZoqMJMuIsaubBo} scale={0.01} />
      <mesh geometry={nodes.BPCrzvlNErACUVK.geometry} material={materials.VOQueNyZsoGeZUR} scale={0.01} />
      <mesh geometry={nodes.XFPsMAgjMKTLfMZ.geometry} material={materials.aNufoLPSlXpHYnK} scale={0.01} />
      <mesh geometry={nodes.pbPTBpYIdQQdDLv.geometry} material={materials.yQNGmZcIpCGQInY} scale={0.01} />
      <mesh geometry={nodes.NnCfUSQVaOFTFYa.geometry} material={materials.ODyLhPZZuAmUwFw} scale={0.01} />
      <mesh geometry={nodes.bSCrRjtqmCsWfPm.geometry} material={materials.OoBOjVVfLatyjvf} scale={0.01} />
      <mesh geometry={nodes.RHMXDtsWqaLKkSb_0.geometry} material={materials.PaletteMaterial002} scale={0.01} />
      <mesh geometry={nodes.aPISBqnewbxiuCV.geometry} material={materials.eoRPGCJmzEkvshY} scale={0.01} />
      <mesh geometry={nodes.CPXxrzevslzkAuF.geometry} material={materials.AuLUvjKzrAufLZb} scale={0.01} />
      <mesh geometry={nodes.msNyfZQPwGEcwcX.geometry} material={materials.jXaGRaRNFlyjRHn} scale={0.01} />
      <mesh geometry={nodes.NQoQJElDSOlUEuE.geometry} material={materials.SQMufwPqPCzZcED} scale={0.01} />
      <mesh geometry={nodes.yOjHmHQnMXTovoC.geometry} material={materials.LfTJxfhwgwSrgMB} scale={0.01} />
      <mesh geometry={nodes.NqkgyPRBeNTKunD.geometry} material={materials.KFjlkFtJpORujtn} scale={0.01} />
      <mesh geometry={nodes.DgUliUcNbuMPdmW.geometry} material={materials.XrUkKndgaNesBlM} scale={0.01} />
      <mesh geometry={nodes.BghuIPCWdvvvIjp_0.geometry} material={materials.BLvlHlhrYfICBWH} scale={0.01} />
      <mesh geometry={nodes.kHKfmfiLxSJMtgM.geometry} material={materials.PaletteMaterial003} scale={0.01} />
      <mesh geometry={nodes.rlReeYefkXxsQFD.geometry} material={materials.LKCtauoVDdOnIYU} scale={0.01} />
      <mesh geometry={nodes.TZFkUZpmqAjMvTD.geometry} material={materials.mXfFpMcDAxXSVTp} scale={0.01} />
      <mesh geometry={nodes.XhNxomnfFrfjBnv.geometry} material={materials.DejKZIOJlLkDHeC} scale={0.01} />
      <mesh geometry={nodes.ScaCdZXyRJjdtLS.geometry} material={materials.VyyPwqsriiuqwJj} scale={0.01} />
      <mesh geometry={nodes.MjpyQECveJvUvLT.geometry} material={materials.guTAJfblFJATcdy} scale={0.01} />
      <mesh geometry={nodes.SOkSaDixThHIBgG_0.geometry} material={materials.MxkvgeKzCcxzyCq} scale={0.01} />
      <mesh geometry={nodes.pdmWYlvORusZbZH_0.geometry} material={materials.LEuDmrSZsictGWp} scale={0.01} />
      <mesh geometry={nodes.fnZWExucUqRQbLq.geometry} material={materials.GsXCMfaPqsYsjoR} scale={0.01} />
      <mesh geometry={nodes.WgCNdmWgTlKwhAK.geometry} material={materials.MFdLyHcwZvhksSo} scale={0.01} />
      <mesh geometry={nodes.etJntyhgDScSLLP.geometry} material={materials.UbpuUjMBkwjeuOX} scale={0.01} />
      <mesh geometry={nodes.kpgSnhkvUFWjBNj.geometry} material={materials.LzRkeMvlHxswAoI} scale={0.01} />
      <mesh geometry={nodes.evxsMxfUHUpJkvC.geometry} material={materials.IxjKatRQmKhcndn} scale={0.01} />
      <mesh geometry={nodes.TTfGeypaoWnhAZq.geometry} material={materials.JuKvRaHxVjuKDTA} scale={0.01} />
      <mesh geometry={nodes.LRzzbMwTzMUgocV.geometry} material={materials.YwpwxTtKpJuhRzG} scale={0.01} />
      <mesh geometry={nodes.CdIqznxmZvylOvB.geometry} material={materials.bQNKwTyRpPfhGLY} scale={0.01} />
      <mesh geometry={nodes.KlqoDCCWjKtGviV.geometry} material={materials.PaletteMaterial004} scale={0.01} />
      <mesh geometry={nodes.YFTTiLOiPWPgzhN.geometry} material={materials.uoSWePiCZJBkFIc} scale={0.01} />
      <mesh geometry={nodes.PVpyAwyTgofkeoe_0.geometry} material={materials.VrkuQrwnFnkyqlN} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/apple_vision_pro-transformed.glb')
